inference_class: LastLayerVI

init_hparams:
  n_posterior_samples: 100

fit_hparams:
  fit_model_hparams:
    n_epochs: 50
    lr: 1e-3
    weight_decay: 0
    dynamic_weight_decay: false
    early_stopping_patience: null
    min_epochs: null
  fit_vi_hparams:
    n_epochs: 50
    lr: 1e-3
    guide: diagonal
    num_particles: 1
    vectorize_particles: false