seed: 0

defaults:
  - inference: monte_carlo_dropout
  - _self_

data:
  data_class: MoonsDataset
  data_hparams:
    batch_size: 100
    n_train: 100
    n_val: 100
    n_test: 100
    noise: 0.1

model:
  model_class: ClassificationFNN
  model_hparams:
    n_in: 2
    n_classes: 2
    hidden_sizes: [5]
    drop_probs: [0.05]
    prior_scale_bias: 1
    prior_scale_weight: 1
    scale_weight_prior_by_dim: False
    device: cuda

data_path: experiments/moons/data
