inference_class: Ensemble

init_hparams:
  n_components: 10

fit_hparams:
  fit_model_hparams:
    n_epochs: 50
    lr: 1e-3
    weight_decay: 0
    dynamic_weight_decay: false
    early_stopping_patience: null
    min_epochs: null