inference_class: NFRefinedLastLayerLaplace

init_hparams:
  n_posterior_samples: 100

fit_hparams:
  fit_model_hparams:
    n_epochs: 50
    lr: 1e-3
    weight_decay: 0
    dynamic_weight_decay: false
    early_stopping_patience: null
    min_epochs: null
  fit_laplace_hparams:
    hessian_structure: full
    optimize_precision: true
  fit_flow_hparams:
    n_epochs: 50
    lr: 1e-3
    transform: Radial
    n_transforms: 5
    num_particles: 1