inference_class: SWAGSVI

init_hparams:
  K: 50
  n_posterior_samples: 100
  sequential_samples: False

fit_hparams:
  fit_model_hparams:
    n_epochs: 50
    lr: 1e-3
    weight_decay: 0
    dynamic_weight_decay: false
    early_stopping_patience: null
    min_epochs: null
  fit_swag_hparams:
    swag_batch_size: null
    swag_epochs: 100
    swag_lr: 1e-3
    clip_value: null
    save_iterates: False,
    val_criterion: accuracy
  fit_covar_hparams:
    svi_lr: 1e-2
    svi_epochs: 100
    mini_batch: false
    n_variational_samples: 100
    sequential_samples: False